# If set to db, then use DB table to store gateways,
# useful when your run many gateways on the same server.
gateways_source: config
environment: test
count_orders: true
expiration_overtime: 0
reuse_address_orders_threshold: 5

gateways:
  default:
    pubkey: 'xpub6Arp6y5VVQzq3LWTHz7gGsGKAdM697RwpWgauxmyCybncqoAYim6P63AasNKSy3VUAYXFj7tN2FZ9CM9W7yTfmerdtAPU4amuSNjEKyDeo6'
    test_pubkey: 'tpubDCzMzH5R7dvZAN7jNyZRUXxuo8XdRmMd7gmzvHs9LYG4w2EBvEjQ1Drm8ZXv4uwxrtUh3MqCZQJaq56oPMghsbtFnoLi9JBfG7vRLXLH21r'
    confirmations_required: 0
    order_class: "StraightServer::Order"
    secret: 'secret'
    check_signature: true
    callback_url: 'http://localhost:3000/payment-callback'
    default_currency: 'BTC'
    orders_expiration_period: 900 # seconds
    exchange_rate_adapters:
      - Bitpay
      - Coinbase
      - Bitstamp
    active: true
    test_mode: true
  second_gateway:
    pubkey: 'xpub6AH1Ymkkrwk3TaMrVrXBCpcGajKc9a1dAJBTKr1i4GwYLgLk7WDvPtN1o1cAqS5DZ9CYzn3gZtT7BHEP4Qpsz24UELTncPY1Zsscsm3ajmX'
    confirmations_required: 0
    order_class: "StraightServer::Order"
    secret: 'secret'
    check_signature: false
    callback_url: 'http://localhost:3001/payment-callback'
    default_currency: 'BTC'
    orders_expiration_period: 300 # seconds
    exchange_rate_adapters:
      - Bitpay
      - Coinbase
      - Bitstamp
    active: true

blockchain_adapters:
  - Insight
  - BlockchainInfo
  - Mycelium

insight_url: "https://insight.mycelium.com/api"
insight_test_url: "https://test-insight.bitpay.com"
  
db:
  adapter: sqlite
  name: straight.db

redis:
  host: localhost
  port: 6379
  # db:   null
  # password: null
